#!/bin/sh

# This script will read your remotes and if you have a remote named pantheon
# it will prompt you to see if you want to sync the pantheon remote

remote="$1"
if [ $remote != "pantheon" ];then
  current_branch=$(git rev-parse --abbrev-ref HEAD)
  flag=`echo $(git remote) |awk '{print match($0, "pantheon")}'`;

  if [ $flag -gt 0 ];then
    echo "FOUND PANTHEON REMOTE"

    exec < /dev/tty

    read -p "Do you wish to push to pantheon as well? (Y/n) " yn
    case $yn in
          Y ) git push pantheon $current_branch; break;;
    esac

    exec <&-

  fi
fi
