#!/bin/sh

#This script will read your remotes and if you have a remote named pantheon
#it will prompt you to see if you want to sync the pantheon remote

#gets the current remote that we are pushing to
remote="$1"

#if the remote is not already pantheon 
#then lets see if there is a pantheon remote
if [ $remote != "pantheon" ];then
  
  #save the current branch we are pushing from
  current_branch=$(git rev-parse --abbrev-ref HEAD)

  #is there a pantheon branch in our remotes list
  flag=`echo $(git remote) |awk '{print match($0, "pantheon")}'`;
  
  #if we found a pantheon remote then lets ask
  #the user if they want to push to pantheon as well
  if [ $flag -gt 0 ];then
    echo "FOUND PANTHEON REMOTE"

    exec < /dev/tty

    read -p "Do you wish to push to pantheon as well? (Y/n) " yn
    case $yn in
          Y ) git push pantheon $current_branch; break;;
    esac

    exec <&-

  fi

fi
